version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword

  redis:
    image: redis:6.2
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=examplepassword
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  existdb:
    image: existdb/existdb:5.3.0
    container_name: existdb
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - existdb_data:/exist-data

volumes:
  dbdata6:
  redis_data:
  elasticsearch_data:
  existdb_data:
